#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}}
REPO=${REPO:-rancher}

cp ../bin/hostname-update-service .
docker build -t ${REPO}/hostname-update-service:${TAG} .

echo Built ${REPO}/hostname-update-service:${TAG}
